# Generated by Django 3.1.3 on 2020-11-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0022_auto_20201104_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
